FROM joyzoursky/python-chromedriver:3.8-selenium

USER root

WORKDIR /neopetHelper
COPY . /neopetHelper/

RUN pip install -r requirement.txt

ENV USERNAME=
ENV PASSWORD=
ENV FAIL_RETRY_SECOND=3600
ENV SUCCESS_NEXT_TIME=3600
ENV PET_LAB2_PETNAME=
ENV PET_TRAINING_PETNAME=
ENV GMAIL_ENABLE=0
ENV GMAIL_APPLICATION_TOKEN=
ENV SENDER_GMAIL=
ENV RECEIVER_EMAIL=

CMD ["python", "dailies.py"]